-- REMOVE TABLE
DROP TABLE IF EXISTS Persons;

-- CREATE NEW TABLE
CREATE TABLE Persons(
    "id" INT NOT NULL,
    "first_name" VARCHAR(50) NOT NULL,
    "birth_date" DATE,
    "phone" VARCHAR(15) NOT NULL,
    CONSTRAINT pk_persons PRIMARY KEY ("id")
);

SELECT * 
FROM Persons;


--  ADD A NEW COLUMN
ALTER TABLE Persons
ADD COLUMN "email" VARCHAR(50) NOT NULL;

SELECT * 
FROM Persons;


-- THEN DELETE THE COLUMN WE HAVE BEEN CREATED BEFORE
ALTER TABLE Persons
DROP COLUMN "email";

SELECT * 
FROM Persons;


-- DELETE THE TABLE
DROP TABLE Persons;